---
title: "Tutorial 4"
author: "Alicia Soh Su Xian"
date: "February 13, 2016"
output: md_document
---

a) Is there any difference in complication rates between patients with good diabetic control and those with poor control?

Risk ratio:

Risk of diabetic complications (Good diabetic control): 3/10

Risk of diabetic complications (Poor diabetic control): 4/6

Risk ratio: (3/10)/(4/6) = 0.45

The value is 0.45 and thus there is a difference in complication rates. Individuals with poor diabetic control have 0.45 times higher risk of getting diabetic complications than individuals with good diabetic control.

b) Determine whether the difference between the two rates is statistically different?

The difference between the two rates are statistically different.

c) Explain why the X2 test should not be used for this study.

X2 should not be used as there should be greater than 5 for each classification for the most appropriate use of chi-square. The chi-square statistic is sensitive to sample size. Most recommend that chi-square not be used if the sample size is less than 50, or in this example, 50 F2 tomato plants. If you have a 2x2 table with fewer than 50 cases many recommend using Fisher's exact test.

